import type { AgriculturalSlide } from './types';

export const AQUASOL_SLIDES: AgriculturalSlide[] = [
  {
    id: 'mobile-command',
    index: '01',
    category: 'Mobile Command',
    title: 'AquaSol Operational Command',
    subtitle: 'IoT telemetry, XGBoost AI advisories & solar gateway sync',
    tagline: 'XGBoost irrigation engine & Gemini advisory in the palm of your hand',
    description:
      'The central operational command center for AquaSol growers. Delivers real-time telemetry from IoT field sensors, autonomous XGBoost irrigation advisories, solar-powered master gateway statuses, multi-lingual controls (EN/HI/KN/TE), and instant Lumi voice assistant integration.',
    metric: {
      value: '86/100',
      label: 'Optimal Farm Health Score',
    },
    technicalSpecs: {
      telemetryRate: '15s Sync',
      solarEfficiency: '100% Solar',
      coverageArea: 'RF Node Mesh',
    },
    tags: ['IoT Telemetry', 'XGBoost AI', 'Solar Gateway', 'Lumi Voice Orb', 'RF Node Mesh'],
    image: '/assets/aquasol-mobile-app.jpg',
    alt: 'AquaSol mobile command app showing real-time farm health score of 86, master gateway telemetry, and field node status',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#eef2e4',
    shortLabel: 'Command',
    accentColor: '#899921',
    accentGlow: 'rgba(137, 153, 33, 0.42)',
    statusBadge: '15s Sync',
  },
  {
    id: 'spatial-zones',
    index: '02',
    category: 'Spatial Farm Hub',
    title: 'Multi-Acre Spatial Intelligence',
    subtitle: 'Plant stress radial gauge, 4-sensor bento & acre mapping',
    tagline: 'Hierarchical spatial telemetry from multi-acre parcels down to single plant stress scores',
    description:
      'The spatial management and crop monitoring engine of AquaSol. Organizes farmland hierarchically from Master Farm Overview and Multi-Acre Spatial Maps down to individual 2x2 Zone quadrants. Features 0–100 Plant Stress Score radial gauges, 4-sensor microclimate bento grids, and independent node actuation.',
    metric: {
      value: '35/100',
      label: 'Plant Stress Score (Critical)',
    },
    technicalSpecs: {
      telemetryRate: '4-Sensor Grid',
      solarEfficiency: 'RF Mesh Synced',
      coverageArea: 'Acre Spatial Map',
    },
    tags: ['Spatial Acre Map', 'Plant Stress Index', 'Microclimate Bento', 'Zone Telemetry', 'Biological Intel'],
    image: '/assets/aquasol-zone-detail.jpg',
    alt: 'AquaSol Zone Detail screen showing Plant Stress Score of 35 Critical, 15.0% soil moisture, and active microclimate bento nodes',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Spatial',
    accentColor: '#e11d48',
    accentGlow: 'rgba(225, 29, 72, 0.38)',
    statusBadge: 'Stress 35',
  },
  {
    id: 'control-actuation',
    index: '03',
    category: 'Control & Scheduling',
    title: 'Autonomous Valve Actuation',
    subtitle: 'AI mode vs manual override, water budget & zone scheduling',
    tagline: 'Bridging machine learning models with direct solenoid valve control & water budget caps',
    description:
      'The actuation and automation command hub of AquaSol. Bridges XGBoost autonomous irrigation models with direct hardware solenoid valve dispatch, 28,000 L daily water budget governance, and multi-zone recurring schedule management with real-time feedback.',
    metric: {
      value: '28.0 kL',
      label: 'Daily Budget Governance',
    },
    technicalSpecs: {
      telemetryRate: 'Instant Dispatch',
      solarEfficiency: 'AI & Manual',
      coverageArea: 'Acre & Zone Grid',
    },
    tags: ['Control Center', 'Water Budget', 'AI Valve Actuation', 'Scheduling Engine', 'Manual Override'],
    image: '/assets/aquasol-control-center.jpg',
    alt: 'AquaSol Control Center screen showing 3.1 kL water budget radial gauge, AI Mode active, and ZoneA automated valve controls',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Actuation',
    accentColor: '#059669',
    accentGlow: 'rgba(5, 150, 105, 0.38)',
    statusBadge: 'AI Auto',
  },
  {
    id: 'analytics-telemetry',
    index: '04',
    category: 'Analytics & Trends',
    title: 'Multi-Zone Data Intelligence',
    subtitle: '7-day water consumption, multi-sensor curves & P&L engine',
    tagline: 'Continuous sensor stream analytics, historical trend baselines & financial P&L tracking',
    description:
      'The core analytical telemetry engine of AquaSol. Delivers multi-zone time-series charting across 4 environmental dimensions (Water, Soil Moisture, Ambient Temp, Humidity), linked IoT node telemetry (MAC address tracking), 7-day volumetric consumption bar charts, and predictive financial P&L analytics.',
    metric: {
      value: '-14%',
      label: 'Weekly Consumption Trend',
    },
    technicalSpecs: {
      telemetryRate: '7-Day Stream',
      solarEfficiency: '4-Vector Analysis',
      coverageArea: 'Zone & Fleet Wide',
    },
    tags: ['Sensor Analytics', 'Water Trends', 'P&L Engine', 'FlChart Engine', 'Hardware Stream'],
    image: '/assets/aquasol-data-analytics.jpg',
    alt: 'AquaSol Data Analytics screen showing 3,150.0 L water consumption, -14% reduction trend, linked hardware MACs, and 7-day telemetry bar chart',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Analytics',
    accentColor: '#0284c7',
    accentGlow: 'rgba(2, 132, 199, 0.38)',
    statusBadge: '-14% Trend',
  },
  {
    id: 'uav-scouting',
    index: '05',
    category: 'UAV Aerial Robotics',
    title: 'Autonomous UAV Canopy Scouting',
    subtitle: '2D GIS flight engine, NDVI thermal heatmaps & RTK GPS',
    tagline: '60 FPS GIS simulation canvas & LoRa RF drone telemetry at 35m AGL',
    description:
      'The autonomous aerial robotics and remote sensing hub of AquaSol. Features a 60 FPS 2D GIS flight simulator with lawnmower survey grids, real-time drone POV camera viewfinders, RTK GPS centimeter positioning (±1.5 cm), multimodal payloads (RGB 4K, Multispectral NDVI, FLIR Thermal), and Raspberry Pi 5 LoRa mesh telemetry.',
    metric: {
      value: '±1.5 cm',
      label: 'RTK GPS Spatial Precision',
    },
    technicalSpecs: {
      telemetryRate: '60 FPS GIS',
      solarEfficiency: '88% Battery',
      coverageArea: '4.2 Ha Swath',
    },
    tags: ['UAV Scouting', 'GIS Flight Engine', 'NDVI Heatmaps', 'RTK GPS (±1.5cm)', 'Raspberry Pi 5 LoRa'],
    image: '/assets/aquasol-uav-scouting.mp4',
    video: '/assets/aquasol-uav-scouting.mp4',
    alt: 'AquaSol UAV Aerial Scouting screen recording showing 2D GIS live flight simulator, lawnmower survey path, and RTK drone telemetry',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Drone GIS',
    accentColor: '#d97706',
    accentGlow: 'rgba(217, 119, 6, 0.42)',
    statusBadge: 'RTK 35m',
  },
  {
    id: 'voice-intelligence',
    index: '06',
    category: 'Conversational AI',
    title: 'Lumi Voice Intelligence',
    subtitle: 'Gemini Live glowing orb, regional TTS & IoT grounding',
    tagline: 'Conversational agronomic copilot grounded in real-time hardware telemetry',
    description:
      'The integrated conversational AI copilot and voice assistant of AquaSol. Powered by Google Gemini and grounded in real-time IoT hardware telemetry, Lumi enables hands-free farm navigation, instant soil moisture and weather queries, and localized agronomic advice across 8 regional languages (EN, HI, KN, TE, TA, MR, GU, BN).',
    metric: {
      value: '8 Languages',
      label: 'Localized Regional TTS/STT',
    },
    technicalSpecs: {
      telemetryRate: 'Real-Time STT',
      solarEfficiency: 'Gemini Live AI',
      coverageArea: 'IoT Grounded',
    },
    tags: ['Lumi Voice Orb', 'Gemini Live', 'Regional STT/TTS', 'IoT Telemetry Grounding', 'Hands-Free Nav'],
    image: '/assets/aquasol-lumi-assistant.jpg',
    alt: 'AquaSol Lumi Voice Assistant screen showing Gemini Live glowing orb, real-time speech waveform, and multilingual controls',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Lumi AI',
    accentColor: '#10b981',
    accentGlow: 'rgba(16, 185, 129, 0.45)',
    statusBadge: 'Gemini Live',
  },
];
