import type { AgriculturalSlide } from './types';

// Copy here describes what each app screenshot shows. Values on the screens
// are examples from the app's own data, not measured results.
export const AQUASOL_SLIDES: AgriculturalSlide[] = [
  {
    id: 'home',
    index: '01',
    category: 'Home',
    title: 'Your whole farm on one screen',
    subtitle: 'Farm health, gateway status and field nodes',
    tagline: 'See what needs attention before you walk the field',
    description:
      'The home screen shows the farm health score, the water used today and how many zones are active. Below it sits the master gateway with its battery, solar input, flow rate and rain reading, followed by each field node. An alert appears at the top when a node goes offline.',
    metric: { value: '86/100', label: 'Farm health score, example screen' },
    technicalSpecs: {
      telemetryRate: 'Farm health score',
      solarEfficiency: 'Gateway battery and solar',
      coverageArea: 'Field node status',
    },
    tags: ['Farm health', 'Master gateway', 'Field nodes', 'Alerts'],
    image: '/assets/aquasol-mobile-app.jpg',
    alt: 'AquaSol home screen with a farm health score of 86 out of 100, the master gateway status and field nodes',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#eef2e4',
    shortLabel: 'Home',
    summary: 'Farm health, water used today and the state of your gateway and field nodes, with an alert when a node drops offline.',
  },
  {
    id: 'farm',
    index: '02',
    category: 'Farm',
    title: 'From the farm down to one zone',
    subtitle: 'Zone detail with a plant stress score and live readings',
    tagline: 'Open a zone to see moisture, temperature, humidity and active nodes',
    description:
      'Farms are organised into zones. Opening a zone shows a plant stress score, the soil moisture reading, temperature and humidity, and how many nodes are active in it.',
    metric: { value: '35/100', label: 'Plant stress score, example zone' },
    technicalSpecs: {
      telemetryRate: 'Plant stress score',
      solarEfficiency: 'Soil moisture',
      coverageArea: 'Temperature and humidity',
    },
    tags: ['Zones', 'Plant stress', 'Soil moisture', 'Nodes'],
    image: '/assets/aquasol-zone-detail.jpg',
    alt: 'AquaSol zone screen with a plant stress score of 35, soil moisture at 15 percent and two active nodes',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Farm',
    summary: 'Drill down from the farm to a single zone and see its stress score, soil moisture, temperature and humidity.',
  },
  {
    id: 'control',
    index: '03',
    category: 'Control',
    title: 'Let the AI water, or take over',
    subtitle: 'AI or manual mode, a daily water budget and a schedule per zone',
    tagline: 'Set the limit once and irrigation stays inside it',
    description:
      'The control center switches between AI mode and manual mode. It shows the daily water budget with the amount used and remaining, then lists each zone with its current state and a schedule.',
    metric: { value: '28,000 L', label: 'Daily water budget, example screen' },
    technicalSpecs: {
      telemetryRate: 'AI or manual mode',
      solarEfficiency: 'Daily water budget',
      coverageArea: 'Schedule per zone',
    },
    tags: ['AI mode', 'Manual override', 'Water budget', 'Schedule'],
    image: '/assets/aquasol-control-center.jpg',
    alt: 'AquaSol control center in AI mode with a 28,000 litre daily water budget and one active zone',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Control',
    summary: 'Let the AI water each zone or take over by hand, within a daily water budget.',
  },
  {
    id: 'data',
    index: '04',
    category: 'Data',
    title: 'Seven days of readings',
    subtitle: 'Water, moisture, temperature and humidity, by zone',
    tagline: 'Spot a trend before it becomes a problem',
    description:
      'The data screen charts the last seven days for water, moisture, temperature and humidity, and can be filtered by zone. It also lists the hardware linked to each zone and shows the change against the previous period.',
    metric: { value: '-14%', label: 'Water use trend, example screen' },
    technicalSpecs: {
      telemetryRate: 'Last 7 days',
      solarEfficiency: 'Water, moisture, temperature, humidity',
      coverageArea: 'Filter by zone',
    },
    tags: ['Trends', 'Water use', 'Sensor readings', 'Linked hardware'],
    image: '/assets/aquasol-data-analytics.jpg',
    alt: 'AquaSol data screen showing 3,150 litres of water used, a 14 percent drop and a seven day bar chart',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Data',
    summary: 'Seven days of water use and sensor readings, filtered by zone.',
  },
  {
    id: 'drone',
    index: '05',
    category: 'Drone',
    title: 'A drone view of the field',
    subtitle: 'Survey path, camera view and stress spots by zone',
    tagline: 'Find the parts of a field that need a closer look',
    description:
      'The drone screen shows the field zone by zone, the drone flying its survey path, and a camera view with vegetation index readings. Zones with signs of nitrogen stress or a moisture deficit are flagged as stress spots. Drone scouting is part of the SIH design; the screen recording here is from the app.',
    metric: { value: '5', label: 'Stress spots flagged, example screen' },
    technicalSpecs: {
      telemetryRate: 'Survey path',
      solarEfficiency: 'Vegetation index overlay',
      coverageArea: 'Stress spots by zone',
    },
    tags: ['Drone', 'Field survey', 'Vegetation index', 'Stress spots'],
    image: '/assets/aquasol-uav-scouting.mp4',
    video: '/assets/aquasol-uav-scouting.mp4',
    poster: '/assets/aquasol-uav-scouting.jpg',
    alt: 'AquaSol drone screen showing eight rice zones, a survey path and flagged stress spots',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Drone',
    summary: 'Follow a drone survey over your zones and see where stress spots were flagged.',
  },
  {
    id: 'assistant',
    index: '06',
    category: 'Lumi',
    title: 'Ask Lumi about your farm',
    subtitle: 'A voice assistant in four languages',
    tagline: 'Speak to Lumi in English, Kannada, Hindi or Telugu',
    description:
      'Lumi listens for questions about soil moisture and zone temperature, and can open screens such as farm analytics by voice. It offers English, Kannada, Hindi and Telugu, and suggests quick actions such as showing analytics or checking zone moisture.',
    metric: { value: '4', label: 'Languages on the Lumi screen' },
    technicalSpecs: {
      telemetryRate: 'Voice questions',
      solarEfficiency: 'English, Kannada, Hindi, Telugu',
      coverageArea: 'Quick actions',
    },
    tags: ['Lumi', 'Voice', 'Kannada', 'Hindi', 'Telugu', 'English'],
    image: '/assets/aquasol-lumi-assistant.jpg',
    alt: 'Lumi voice assistant screen listening for a question, with language choices English, Kannada, Hindi and Telugu',
    imagePosition: 'top center',
    imageFit: 'cover',
    overlayTheme: 'app-screen',
    bgColor: '#fafbf5',
    shortLabel: 'Lumi',
    summary: 'Ask Lumi about soil moisture or temperature in English, Kannada, Hindi or Telugu.',
  },
];
